export const ORDER_ACTION_TYPE = {
  FETCH_ORDER_START: 'order/FETCH_ORDER_START',
  FETCH_ORDER_SUCCESS: 'order/FETCH_ORDER_SUCCESS',
  CREATE_ORDER_SUCCESS: 'order/CREATE_ORDER_SUCCESS',
  UPDATE_ORDER_SUCCESS: 'order/UPDATE_ORDER_SUCCESS',
  FETCH_ORDER_FAILED: 'order/FETCH_ORDER_FAILED',
}