version: '3.9'
services:
  dbshop:
    image: postgres:11
    environment:
      - NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - shopt2t_data:/var/lib/t2tshop/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=django-insecure-_ef2tlrmrgxy2xxcc1o^=_kxyi%=h6)x71kbbm)%r5cxf8wjxv
      - DEBUG=0
      - NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - dbshop  

volumes:
  shopt2t_data: