export const ACTION_CART_TYPE = {
  CART_UPDATE: 'cart/CART_UPDATE',
  CART_OPEN: 'cart/CART_OPEN',
  CART_CLEAR: 'cart/CART_CLEAR',
  CART_FETCH_COUPON_START: 'cart/CART_FETCH_COUPON_START',
  CART_FETCH_COUPON_SUCCESS: 'cart/CART_FETCH_COUPON_SUCCESS',
  CART_FETCH_COUPON_FAILD: 'cart/CART_FETCH_COUPON_FAILD',
}
