export const PROFILE_ACTION_TYPE = {
  FETCH_PROFILE_START: 'profile/FETCH_PROFILE_START',
  FETCH_PROFILE_SUCCESS: 'profile/FETCH_PROFILE_SUCCESS',
  CREATE_PROFILE_SUCCESS: 'profile/CREATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_SUCCESS: 'profile/UPDATE_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILED: 'profile/FETCH_PROFILE_FAILED',
}