export const PROMOTIONS_ACTION_TYPES = {
  FETCH_PROMOTIONS_START: 'promotions/FETCH_PROMOTIONS_START',
  FETCH_PROMOTIONS_SUCCESS: 'promotions/FETCH_PROMOTIONS_SUCCESS',
  FETCH_PROMOTIONS_FAILED: 'promotions/FETCH_PROMOTIONS_SUCCESS',
}