# Generated by Django 3.2.16 on 2022-11-02 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/category/%Y-%m-%d'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_slug', models.SlugField(default=uuid.uuid1, max_length=150, unique=True)),
                ('product_image', models.ImageField(blank=True, upload_to='iamge/product/%Y-%m-%d')),
                ('product_price', models.FloatField(blank=True, default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
            ],
        ),
    ]
