# Generated by Django 3.2.16 on 2022-11-03 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221102_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoto_name', models.CharField(max_length=150)),
                ('promoto_slug', models.SlugField(default=uuid.uuid1, max_length=150, unique=True)),
                ('promoto_expiration', models.DateTimeField()),
                ('promoto_rate', models.FloatField(blank=True, default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
        ),
    ]
