# Generated by Django 3.2.16 on 2022-11-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221103_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion_expiration',
            new_name='promoto_expiration',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion_name',
            new_name='promoto_name',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion_rate',
            new_name='promoto_rate',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='promotion_slug',
            new_name='promoto_slug',
        ),
    ]
