# Generated by Django 3.2.16 on 2022-11-10 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColectFilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=150, unique=True)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
