# Generated by Django 3.2.16 on 2022-11-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'len don'), ('on_way', 'dang tren duong'), ('delivered', 'da giao')], default='ready', max_length=50)),
                ('subtotal', models.PositiveBigIntegerField(blank=True)),
                ('total', models.PositiveBigIntegerField(blank=True)),
                ('delivery_fee', models.PositiveSmallIntegerField(default=30000)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('profile_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('color_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.color')),
                ('order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.products')),
                ('size_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.collectsize')),
            ],
        ),
    ]
