# Generated by Django 3.2.16 on 2022-11-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='app.color'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='app.products'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='app.collectsize'),
        ),
    ]
