# Generated by Django 3.2.16 on 2022-11-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20221123_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
