# Generated by Django 3.2.16 on 2022-11-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
    ]
