# Generated by Django 3.2.16 on 2022-11-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20221125_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='app.discount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
