# Generated by Django 3.2.16 on 2022-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_products_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['update']},
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
