# Generated by Django 3.2.16 on 2022-11-27 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20221125_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('value', models.PositiveIntegerField(blank=True, default=0)),
                ('active', models.BooleanField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
