# Generated by Django 3.2.16 on 2022-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
