# Generated by Django 3.2.16 on 2022-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_order_coupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_value',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
