# Generated by Django 3.2.16 on 2022-12-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='views',
            name='product_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.products'),
        ),
    ]
