# Generated by Django 3.2.16 on 2022-12-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20221201_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-create']},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='iamge/blog/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='image/product/%Y-%m-%d'),
        ),
    ]
