# Generated by Django 3.2.16 on 2022-12-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20221212_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='image/blog/%Y-%m-%d'),
        ),
    ]
